1. Ren Python statistik. Skriv en funktion stats(tal), der tager en liste og returnerer gennemsnit, median og standardafvigelse uden at importere noget. Test den på [4, 8, 15, 16, 23, 42] og sammenlign med np.mean, np.median og np.std. Skriv i en markdown celle, hvorfor din standardafvigelse eventuelt afviger. Hint: læs om parameteren ddof.

In [6]:
tal = [4, 8, 15, 16, 23, 42];

def stats(tal):
    tal.sort()
    gennemsnit = sum(tal) / len(tal)
    median = tal[len(tal) // 2]
    standardafvigelse = (sum((x - gennemsnit) ** 2 for x in tal) / (len(tal) - 1)) ** 0.5
    return gennemsnit, median, standardafvigelse

print(stats(tal))
a=np.mean(tal)
b=np.median(tal)
c=np.std(tal)
print(a,b,c)

(18.0, 16, 13.490737563232042)
18.0 15.5 12.315302134607444


Standardafvigelse afviger grundet ddof parameteren som er inkluderet i numpy. Ddof beskriver degrees of freedom. Når man bruger numpy til at beregne standardafvigelsen, beregner den den med N-1 frihedsgrader, hvorfor tallet derfor er anderledes.

> Tilføj citatblok



2. NumPy indeksering. Lav med np.random.default_rng(42) en 5 x 4 matrix med heltal fra 0 til 99. Udtræk række 2, kolonne 3 og den nederste højre 2 x 2 blok. Brug en boolean mask til at finde alle værdier over 50. Beregn gennemsnittet pr. kolonne og pr. række med axis. Reshape matricen til 2 x 10.

In [1]:
import numpy as np
rng = np.random.default_rng(42)
matrix = rng.integers(0, 100, size=(5, 4))
print(matrix)
print(matrix[1, 2])
print(matrix[-2:, -2:])
print(matrix[matrix > 50])
print(np.mean(matrix, axis=0))
print(np.mean(matrix, axis=1))
print(matrix.reshape(2, 10))

[[ 8 77 65 43]
 [43 85  8 69]
 [20  9 52 97]
 [73 76 71 78]
 [51 12 83 45]]
8
[[71 78]
 [83 45]]
[77 65 85 69 52 97 73 76 71 78 51 83]
[39.  51.8 55.8 66.4]
[48.25 51.25 44.5  74.5  47.75]
[[ 8 77 65 43 43 85  8 69 20  9]
 [52 97 73 76 71 78 51 12 83 45]]


3. Loop mod vektorisering. Beregn summen af kvadraterne af 1.000.000 tilfældige tal, først med en for løkke og derefter med NumPy. Tag tid på begge med time eller %timeit, og skriv hvor mange gange hurtigere NumPy er.

In [16]:
import numpy as np
import time
summen_loop=0
summen_np=0

rng=np.random.default_rng(42)
x=rng.random(1000000)
x_liste=x.tolist()

start_loop=time.perf_counter()
for i in x_liste:
    summen_loop += i**2
slut_loop=time.perf_counter()
print(summen_loop)
tid_loop=slut_loop-start_loop
print(tid_loop)


start_np=time.perf_counter()
summen_np=np.sum(x**2)
slut_np=time.perf_counter()
print(summen_np)
tid_np=slut_np-start_np
print(tid_np)

print(np.isclose(summen_loop, summen_np))

faktor=tid_loop/tid_np
print(faktor)


333336.88488524745
0.15302232900012314
333336.8848852429
0.002653955999903701
True
57.65820119311532


Numpy er altså 57,6 gange hurtigere end python

4. Matrixprodukt i hånden. Skriv en funktion med indlejrede løkker, der ganger en 2 x 3 matrix med en 3 x 2 matrix. Tjek resultatet mod A @ B. Forklar i en markdown celle, hvorfor formen på resultatet bliver 2 x 2.

In [29]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8], [9, 10], [11, 12]])
print(a)
print(b)

matrixprodukt_np= np.matmul(a,b)
print(matrixprodukt_np)

def matrixprodukt(a, b):
    c = np.zeros((a.shape[0], b.shape[1]))
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                c[i, j] += a[i, k] * b[k, j]
    return c

matrixprodukt_loop=matrixprodukt(a,b)
print(matrixprodukt_loop)



[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]
[[ 58.  64.]
 [139. 154.]]


Grunden til at det bliver en 2x2 matrix er at man tager produktet af række 1 i a med kolonne 1 i b for at få punkt (1,1). Dette gør man også med række 2 og kolonne 1 osv. Dermed ender man op med kun at have en 2X2 matrix.

5. Refleksion. Skriv 5 til 10 linjer i REFLEKSION.md: hvad der var svært, hvad du lærte, og hvorfor vektorisering betyder noget i ML.